# Generated by Django 5.1.7 on 2025-03-15 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinicians.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'clinician', 'start_date'), name='unique_patient_clinician_appointment'), models.UniqueConstraint(fields=('clinician', 'start_date'), name='unique_clinician_appointment'), models.UniqueConstraint(fields=('patient', 'start_date'), name='unique_patient_appointment')],
            },
        ),
    ]
