services:    
  restapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-docker
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  sqlite_data: