services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web-container
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules